[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/components"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv", "gcc"] 